### ISSUE TITLE
You might need to have better labels because i cant find the right script in here to use. I don't know if its just broken or im using the wrong thing

### ISSUE THREAD

**Issue by 1nsan1tywashere** [CPScript/Kitty-Tools#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CPScript** [comment]
their is no reason for a bookmaklet... it runs in the Terminal
?????

**Comment by 1nsan1tywashere** [comment]
Should i be able to put the script into a book mark like some others. Im trying to do some stuff on a school device. all i got is just bookmarklets to have fun. Is are these bookmarklet scripts to begin with?

**Comment by CPScript** [comment]
Thats called a "bookmarklet" (A browser bookmark for chome OS made using java) (I have a couple) and NO its not a bookmark, read how to use the tool on the lower half of the page.
