### ISSUE TITLE
Http error 404

### ISSUE THREAD

**Issue by noobthepro500** [CPScript/Kitty-Tools#20]
**Describe the bug**
When the quiz id is put in it says http error 404 not found
**To Reproduce**
1. Python main.py
2. 4
3. Put in quiz id

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CPScript** [comment]
> **Describe the bug** A clear and concise description of what the bug is. When the quiz id is put in it says http error 404 not found **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Python main.py
> 2. 4
> 3. Put in quiz id
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

you might not have typed the quiz ID in correctly... oone thing it might be is because the kahoot was recently created.
