### ISSUE TITLE
File creation error

### ISSUE THREAD

**Issue by Luky12568** [CPScript/Kitty-Tools#30]
**Describe the bug**
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Kitty-Tools/Kahoot/kahoot.py", line 121, in <module>
    open(data_path, "x")
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/home/Kitty-Tools/Kahoot/quizzes/c2adced8-47f9-4ab7-8bae-89729a1b6aaa.json'

**To Reproduce**
1. Run it to the end and you see it

**Expected behavior**
Save it to a file???

**Screenshots**
![Screenshot_20231006-142354_Termux.jpg](https://github.com/CPScript/Kitty-Tools/assets/75023813/2dc4e37e-70b1-4dc2-afc5-18f787634d5c)

 

**Smartphone (please complete the following information):**
 - Device: Samsung A41
 - OS: Android 11
 - Browser: Chrome, ran it on Termux
 - Version: idk

**Additional context**
Tried to chmod it but nothing also I tried w and not x

**Comment by CPScript** [comment]
since you ran it on termux it cant backup the file... it will still work perfectly fine, please ignore this issue as this issues will happen on certain devices

**Comment by CPScript** [comment]
i would recommend installing root and letting termux have access to external storage:
`pkg install root-repo`
`termux-setup-storage`

doing such might help

**Comment by CPScript** [comment]
also, charge your phone :D
