### ISSUE TITLE
Errors At Run.

### ISSUE THREAD

**Issue by Ihasabucket8950** [CPScript/Kitty-Tools#39]
**Describe the bug**
Code Errors In Main.py, Sprint.py, and Colors.py

**To Reproduce**

- git clone https://github.com/CPScript/Kitty-Tools
- cd Kitty-tools
- python main.py

**Screenshots**
![image](https://github.com/CPScript/Kitty-Tools/assets/91221215/26e333f4-1a4e-4030-b091-6daf9fa440b6)

**Laptop (please complete the following information):**
 - OS: [Windows 10 Education]
 - Browser [Opera GX]
 - Version [22H2]

**Additional context**
Followed directions on Readme.md and got this error.

**Comment by Ihasabucket8950** [comment]
Nevermind, sorry i just had to run the code twice to get it to work.

**Comment by CPScript** [comment]
lol
