### ISSUE TITLE
Not downloading on Windows 10

### ISSUE THREAD

**Issue by JackWagon885** [CPScript/Kitty-Tools#60]
**Describe the bug**
Whenever I try to install it with pip install git clone https://github.com/CPScript/Kitty-Tools on command prompt with admin it always says "ERROR: Cannot unpack file C:\Users\jackw\AppData\Local\Temp\pip-unpack-ppmxn724\Kitty-Tools (downloaded from C:\Users\jackw\AppData\Local\Temp\pip-req-build-3c1t733f, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\jackw\AppData\Local\Temp\pip-req-build-3c1t733f".

**To Reproduce**
Type "pip install git clone https://github.com/CPScript/Kitty-Tools" into command prompt with admin privileges.

**Screenshots**
![image](https://github.com/CPScript/Kitty-Tools/assets/148831953/2bf401bf-4cc0-492a-8bd5-78cae5163b33)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge

**Additional context**
I tried using the Python cmd prompt too

**Comment by CPScript** [comment]
Please do this...

First - install python(already done)
Second install git - `pkg install git`
Third - type `git clone {repo link}`

Instead of - `pip install git clone {repo link}`

**Comment by JackWagon885** [comment]
Tried it, didn't work

**Comment by JackWagon885** [comment]
I typed git clone https://github.com/CPScript/Kitty-Tools into cmd & python (admin)

**Comment by CPScript** [comment]
Did you install git?

**Comment by JackWagon885** [comment]
command did nothing in same senerios

**Comment by MrShadowDev** [comment]
> command did nothing in same senerios

Search on google git and download it so you can do it. Or just download it zipped and uncompress it.

**Comment by JackWagon885** [comment]
After downloading GIT from online, then used the "git clone https://github.com/CPScript/Kitty-Tools.git" command in cmd prompt as administrator, followed by the other commands, it worked! I had to run "python main.py" twice though.

**Comment by JackWagon885** [comment]
After downloading GIT from online, then used the "git clone https://github.com/CPScript/Kitty-Tools.git" command in cmd prompt as administrator, followed by the other commands, it worked! I had to run "python main.py" twice though.
