### ISSUE TITLE
[FLOODER & ANSWER HACK] Not Working

### ISSUE THREAD

**Issue by MrShadowDev** [CPScript/Kitty-Tools#61]
![image](https://github.com/CPScript/Kitty-Tools/assets/71973368/8f68c916-b568-4eb5-a9e3-e36f150e297e)

Answer Hack doesnt even load...

**Comment by CPScript** [comment]
Please use the issue template

**Comment by CPScript** [comment]
![Screenshot_20240206-071619.png](https://github.com/CPScript/Kitty-Tools/assets/83523587/c6a6ec2c-8857-40ca-8737-0a7148e939be)

**Comment by MrShadowDev** [comment]
Executed main.py and choosed number and throw that error. I'm using Windows 10

**Comment by KiraKenjiro** [comment]
Hola Shadow,

Sólo voy a ayudarte aquí como CPS es un poco ocupado en este momento.
¿Puedes intentar una instalación clen para mí, parece que un archivo no se puede encontrar. Asegúrese de que tiene los dependencys instalado como nodejs y los módulos de python y tal.

**Comment by CPScript** [comment]
thank you

**Comment by CPScript** [comment]
please try this: 

Install python `pkg install python`
Install git `pip install git`
Clone the repo `git clone {repo}`
Go to repo dir `cd Kitty-Tools`
Run script `python main.py`

> note - The flodder doesn't work and i will make one soon

**Comment by CPScript** [comment]
if `pkg install python` doesn't work you can install python 3.11 from its website

**Comment by CPScript** [comment]
## NOTE
> you will need to be root, do this by typing `su` into your CMD

**Comment by CPScript** [comment]
> please try this:
> 
> Install python `pkg install python` Install git `pip install git` Clone the repo `git clone {repo}` Go to repo dir `cd Kitty-Tools` Run script `python main.py`
> 
> > note - The flodder doesn't work and i will make one soon

btw, this is to re install everything as this is what i have done to install it using windows 10, this might not fix the error and i will look into the error you got later (im at school atm)

**Comment by MrShadowDev** [comment]
> ## NOTE
> > you will need to be root, do this by typing `su` into your CMD

I'm not root...

**Comment by CPScript** [comment]
please send a video of you recreating such error <3
(this is required so i can fix it)

**Comment by MrShadowDev** [comment]
> please send a video of you recreating such error <3 (this is required so i can fix it)

Sure. Option 4 I don't have a Kahoot ID right now so i couldnt record it.

https://github.com/CPScript/Kitty-Tools/assets/71973368/abd1d458-cd5e-4b4c-93cd-726ade88caa5

**Comment by CPScript** [comment]
thanks... you will need to run the script using the file in the kitty tools folder, also... the flooder doesn't work
