### ISSUE TITLE
Typed in right ID but it still isnt working

### ISSUE THREAD

**Issue by BErADeatscheese** [CPScript/Kitty-Tools#63]
<img width="663" alt="Screenshot 2024-02-11 100552" src="https://github.com/CPScript/Kitty-Tools/assets/127018067/ffe946aa-175b-46b5-8fdc-500edaa55971">

**Comment by CPScript** [comment]
"Clear" is a Linux command sadly... I will fix this soon

**Comment by CPScript** [comment]
FIXED, please try again (might be buggy)
