### ISSUE TITLE
Getting some kind of file error and undefined variable

### ISSUE THREAD

**Issue by smashbombs** [CPScript/Kitty-Tools#73]
<img width="906" alt="Screenshot 2024-03-12 at 1 44 47 pm" src="https://github.com/CPScript/Kitty-Tools/assets/99016321/3553d8ff-0f38-4236-be30-800826096f75">
<img width="539" alt="Screenshot 2024-03-12 at 1 49 29 pm" src="https://github.com/CPScript/Kitty-Tools/assets/99016321/7896b18b-8076-4441-91c4-a4ead362219f">

**Comment by smashbombs** [comment]
This happens for all options, and I have tried editing the code, but it just breaks more. I would appreciate some help.

**Comment by smashbombs** [comment]
I managed to get further, but now I get a "HTTP Error 400: Bad Request" error when trying to use the answer bot. It is also the only one that gets further.

**Comment by CPScript** [comment]
I currently don't have access to my GitHub account nor any of my other
accounts so I can't help you BUT I wish you the best of luck with fixing
the issue♥️

**Comment by CPScript** [comment]
you need to download pytython...
