### ISSUE TITLE
Can you make a youtube Totorial for Linux

### ISSUE THREAD

**Issue by Harpan12** [CPScript/Kitty-Tools#79]

**Comment by Harpan12** [comment]
*Tutorial*

**Comment by CPScript** [comment]
Sure, I will when I get the chance 😊

**Comment by Harpan12** [comment]
👍

**Comment by CPScript** [comment]
I didn't make a YouTube tutorial, but I did add a video tutorial to https://GitHub.com/CPScript/Kitty-Tools/Readme.md
