### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Luky12568** [CPScript/Kitty-Tools#80]
Womp Womp!                                                                        There was an error!  Mabey you typed the 'Quiz ID' incorrectly!                                                                                                     'answer'

Ran the main.py on termux..... the lite works, but i wanted to see the answers....

**Comment by Luky12568** [comment]
I modded it, here is the throwback:
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Kitty-Tools/Kitty/client.py", line 189, in <module>
    start_kahoot()
  File "/data/data/com.termux/files/home/Kitty-Tools/Kitty/client.py", line 180, in start_kahoot
    print(f"{pretty}{orange}[{reset}Question{orange}]{green}--{orange}[{reset}{kahoot.get_question_names()[i]}{orange}]{reset}\n{pretty}{orange}[{reset}Answer{orange}]{green}--{orange}[{reset}{', '.join(kahoot.get_answer(i))}{orange}]{reset}\n")
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Kitty-Tools/Kitty/client.py", line 87, in get_question_names
    if self.get_question_details(i)["type"] == "content":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Kitty-Tools/Kitty/client.py", line 112, in get_question_details
    self.data["questions"][question]["choices"][i]["answer"] = self.data["questions"][question]["choices"][i]["answer"].replace('"', '\\"').replace("<p>", "").replace("</p>", "").replace("<strong>", "").replace("</strong>", "").replace("<br/>", "\n").replace("</span>", "").replace("</mo>", "").replace("</mrow>", "").replace("<mn>", "").replace("</mn>", "").replace("</annotation>", "").replace("</semantics>", "").replace("</math>", "").replace("<span>", "").replace("<math>", "").replace("<semantics>", "").replace("<mrow>", "").replace("<mo>", "").replace("<msup>", "").replace("<mi>", "").replace("</mi>", "").replace("</msup>", "").replace("<b>", "").replace("</b>", "")
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'answer'

**Comment by CPScript** [comment]
Can you please use the template so I can help?

**Comment by CPScript** [comment]
Hmm, I don't see the template.... That's weird
