### ISSUE TITLE
unterminated triple-quoted string literal

### ISSUE THREAD

**Issue by ezie0** [CPScript/Kitty-Tools#81]
Hi there! I get this error on Android:

![Screenshot_20240514_111644_Termux.jpg](https://github.com/CPScript/Kitty-Tools/assets/169771062/a0ac12bf-06e8-44ad-8abd-41d80ebfcaee)

Am I missing something?

**Comment by CPScript** [comment]
Try re running it

**Comment by CPScript** [comment]
I have fixed this error :D

**Comment by ezie0** [comment]
Hi, thank you so much! <3
