### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Luky12568** [CPScript/Kitty-Tools#82]
The true and false is reversed, so just letting you know. Btw question name and answer name when in lite?

**Comment by Luky12568** [comment]
Yes, I have the latest version

**Comment by Luky12568** [comment]
i asked about the feature in [issue 74](https://github.com/CPScript/Kitty-Tools/issues/74)

**Comment by CPScript** [comment]
Lite is supposed to be simple so it won't get updated to how the main version is... Plus ill fix the true and false error when I get the chance
