### ISSUE TITLE
Auto Answer Not Working

### ISSUE THREAD

**Issue by BowLuckie** [CPScript/Kitty-Tools#89]
i had to manually install some dependences but auto answer still wasn't working

`
       _______________________
      || Enter your quiz ID  ||
      || below! <3           ||
      |//
(>﹏<)
--------------------------------------
---- Kitty-Tools | By <> CPScript ----
--------------------------------------

┌─[Enter Kahoot-ID] <> [User-Input]
└─────► 687607
(!) Fetching Answers From: [Quiz-ID: 687607]

'clear' is not recognized as an internal or external command,
operable program or batch file.
Womp Womp!
There was an error!  Mabey you typed the 'Quiz ID' incorrectly!

'bool' object is not subscriptable

||=========================================================
||Thanks for using Kitty-Tools <3
||Please *STAR* this repo and follow the creator on github!
||=========================================================

Press any key to exit...
`

i dont know if this is my fault but i cant install dependency's that allow bool to be subtractable

**Comment by CPScript** [comment]
You need to type the quiz id in the search bar... Not the join code
