### ISSUE TITLE
how do i use it?

### ISSUE THREAD

**Issue by echtnietbas1** [CPScript/Kitty-Tools#90]
-----Version-36.2-----
/1/ How to use | Shows you how to use the tool
/2/ Information | Credits, licence, and more
/3/ Flooder | Flood a Kahoot game (Not working)
/4/ Answer Hack | Start the answer client
---------------------- 

i have this screen what now?

**Comment by CPScript** [comment]
Type in number 4

**Comment by echtnietbas1** [comment]
> Type in number 4

doesn't work, I get 'Number' is not recognized as an internal or external command,
operable program or batch file.

**Comment by echtnietbas1** [comment]
It works now, but is says give the game ID. but that's not going to work in class. Do you have any ideas how I am going to get the ID without looking at the host screen?

**Comment by CPScript** [comment]
I recommend looking online for a tool that can do such... I personally haven't implemented such a tool yet, but I'm planning on it.

**Comment by echtnietbas1** [comment]
th
